### ISSUE TITLE
Audible player not recognised 

### ISSUE THREAD

**Issue by redimongo** [sanchezzzhak/node-device-detector#129]
I just tried the example and the following did not pick up Audible.
This is the user-agent. I would of pulled and made a update, however I can't find the file you put all the player in.

```
Audible, Android, 3.42.0, samsung, SM-S908E, b0qxxx, 13, 1.0, WIFI
```

Also this user-agent is saying it's IOS however it's not defined.

```
Overcast/1.0 Podcast Sync (+http://overcast.fm/)
```

**Comment by sanchezzzhak** [comment]
Hi.
adding new data needs to be added to the https://github.com/matomo-org/device-detector, later they will be synchronized with this repository.

fixture for detection
https://github.com/matomo-org/device-detector/blob/master/regexes/client/mobile_apps.yml
and exsample tests
https://github.com/matomo-org/device-detector/blob/master/Tests/Parser/Client/fixtures/mobile_app.yml


`Overcast/1.0 Podcast Sync (+http://overcast.fm/)` - this is a service bot
https://overcast.fm/podcasterinfo
```
User-Agents
Overcast’s iOS app uses the following HTTP User-Agent string for its episode downloads:

Overcast/3.0 (+http://overcast.fm/; iOS podcast app)
The Apple Watch app uses the following User-Agent for its episode downloads:

Overcast (+http://overcast.fm/; Apple Watch podcast app)
Keep in mind that a listener may download an episode from multiple devices.

Crawling your feed
Overcast uses server-side crawling, centrally fetching your RSS feed for all Overcast listeners to deliver new episodes faster and save bandwidth.

Each listener still downloads your audio directly from your servers. Overcast does not cache, re-host, or re-serve audio to listeners, but you may see Overcast’s servers download episodes to collect metadata.

Please ensure that these servers are not blocked:

crawl1.overcast.fm
crawl2.overcast.fm
crawl3.overcast.fm
crawl4.overcast.fm
crawl5.overcast.fm
crawl6.overcast.fm
They update feeds at varying intervals from a few minutes to 24 hours, depending on their popularity. Standard HTTP caching headers are obeyed.

Subscriber counts are reported in the HTTP User-Agent string, e.g.:

Overcast/1.0 Podcast Sync (123 subscribers; feed-id=456789; +http://overcast.fm/)
```

Will you be able to add PR to that https://github.com/matomo-org/device-detector repository?
