### ISSUE TITLE
Differenciation native app and web browser

### ISSUE THREAD

**Issue by foch01** [sanchezzzhak/node-device-detector#139]
Hello,

The project is very interesting! ! I have a little question, It's possible to differentiate if the request comes from a web browser or a native iOS application for example ?

**Comment by sanchezzzhak** [comment]
Hi, Thanx.

The user agents we know are defined as mobile applications.
Theoretically, for applications that use UIWebView, you can check the result separately.

UIWebView
Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_1 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Mobile/8B117
Mozilla/5.0 (iPad; CPU OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D201
Mozilla/5.0 (iPhone; CPU iPhone OS 16_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_9 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148


Safari
Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1

AppleMail
Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) BC3 iOS/3.12.7 (build 538; iPhone 11 Pro Max; iOS 14.7.1)

something like this
```js
let result = detector.detect(userAgent);
let hasUIWebView = result.client && result.client.name === 'Safari' && result.device && ['smartphone', 'tablet'].indexOf(result.device.type) !== -1 && /AppleWebKit(?!.*Safari)/i.test(userAgent);
if (hasUIWebView) {
    result.client.name = 'UIWebView';
}
```

**Comment by foch01** [comment]
Ok for Web view UI only. Only I have an API which is requested by a native iOS app in Swift UI and a Safari browser. I would like to be able to tell the 2 apart. It's possible ?

**Comment by sanchezzzhak** [comment]
Without a user agent, I can't help.
Most likely UA, will be the same Safari

**Comment by foch01** [comment]
Infact I have to add a specific regex depending on the type of user-agent that my iOS app sends if I understand correctly.

I thought that we could detect with the default user-agent that a mobile app could send us if it was an iOS or android mobile app.


My iOS app must send, for example:

**MyApp**/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) BC3 iOS/3.12.7 (build 538; iPhone 11 Pro Max; iOS 14.7.1)

To detect it as an iOS app using a regex like in the example you sent above.
Sorry, I'm newbie to the world of user-agent...

**Comment by sanchezzzhak** [comment]
For Android, everything is simple, all sites that open in the WebView of the application send a special header x-requested-with.

One way is to update the UA in your app by adding information that you think is necessary, such as the app name/version
The two way is to send the X-Client header.
And for that, you don't need a detector. 
You can simply check the header on your website or UA for the occurrence of string app-name/version

> node-device-detector is designed to get the device name, os+version, browser, device type
> With the data you receive, you do whatever you want
> From personal experience, we use detector in the sale of advertising on websites.
> Someone buys traffic, say, only mobile devices, someone buys certain browsers.

**Comment by foch01** [comment]
Sorry, I don't understand why you are talking about webview.

I want to be able to retrieve a user's device on a native iOS and Android app, not from a webview.

**Comment by AwaludinAR** [comment]
I believe you simply need to provide an additional user agent or header to the application for each request made to the server. Subsequently, on the server side, you only need to perform parsing to determine the origin of the incoming request.

**Comment by AwaludinAR** [comment]
> Sorry, I don't understand why you are talking about webview.
> 
> I want to be able to retrieve a user's device on a native iOS and Android app, not from a webview.

Are you using a framework for native apps, such as React Native, Quasar, or others?

**Comment by sanchezzzhak** [comment]
a year has passed, I am closing this issue.
