### ISSUE TITLE
Desktop user agents do not give device output

### ISSUE THREAD

**Issue by mayurbhole** [sanchezzzhak/node-device-detector#6]
For User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537`
It does not give device output. It should give `device` as `desktop`.
On website (http://devicedetector.net), it shows device as `desktop`.

**Comment by sanchezzzhak** [comment]
Hi, I'm working on this error, this error is fixed in this branch "browser_engine_port"

**Comment by mayurbhole** [comment]
Hi Tutik Alexsandr, Thanks for the fix. Can you please provide updated npm package for this??

**Comment by sanchezzzhak** [comment]
Hi, not yet, a small portion of the test still produces the error. http://take.ms/Gw0vMg
Work continues  ==> stable tests
