### ISSUE TITLE
import instead of require

### ISSUE THREAD

**Issue by MickL** [sanchezzzhak/node-device-detector#75]
When importing in TypeScript:

```
import DeviceDetector from 'node-device-detector';

const detector = new DeviceDetector();
```

I get the error:
> node_device_detector_1.default is not a constructor

I also tried:
```
import * as DeviceDetector from 'node-device-detector';

const detector = new DeviceDetector();
```

Which gives a TypeScript error:
> TS2351: This expression is not constructable.   Type 'typeof import("node-device-detector")' has no construct signatures.

But the latter works when adding `// @ts-ignore`, so there must be something wrong with the typings?

**Comment by sanchezzzhak** [comment]
if delete files   'node-device-detector/index.d.ts' and  'node-device-detector/helper.d.ts' 
```
import DeviceDetector = require('node-device-detector');
const detector = new DeviceDetector();

const userAgent = 'Mozilla/5.0 (Linux; Android 5.0; NX505J Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.78 Mobile Safari/537.36';
const result = detector.detect(userAgent);
console.log('result parse', result);
```
then, everything works.

TypeScript is not my strong suit :horse: , but I'll see what I can do.

**Comment by sanchezzzhak** [comment]
Since project has only interfaces and types for TS, it is necessary to use `// @ts-ignore` for constructor class.
I've also updated index.d.ts  for clienthints

https://github.com/sanchezzzhak/node-device-detector/blob/master/docs/TYPE_SCRIPT.MD

**Comment by MickL** [comment]
In my opinion it should never be necessary to use `// @ts-ignore`. Within a lot of projects it is also forbidden to use by eslint rules.

The problem is that your package comes with types that are not correct. The typings need to be corrected, please reopen this issue, maybe someone will make a PR some day.

**Comment by sanchezzzhak** [comment]
To fix this, need to completely redo all files in typescript.
I'm not ready to support this TypeScript. (fully)

If someone knows how to solve it through the declaration of classes https://github.com/sanchezzzhak/node-device-detector/blob/884dab2c636d8ce161768b6fbba7081e5e2fe1db/index.d.ts#L5-L9, share in this topic.

**Comment by sanchezzzhak** [comment]
https://github.com/sanchezzzhak/demo-node-device-detector/blob/master/src/index.ts

so far, it only works with such a configuration.
there are no plans to rework the project on erxpot/import

https://github.com/sanchezzzhak/demo-node-device-detector/blob/master/tsconfig.json

**Comment by phatnt93** [comment]
You can try to add "esModuleInterop": true, into tsconfig.json

**Comment by gabrielyncas** [comment]
While this is not fixed, this is a workaround to import, use and preserve the "correct" types from the lib (if you can use `// @ts-ignore`):

```ts
import DeviceDetector from 'node-device-detector'

// @ts-ignore
const detector: DeviceDetector.default = new DeviceDetector({
  clientIndexes: true,
  deviceIndexes: true,
  osIndexes: true,
  deviceAliasCode: true,
  deviceTrusted: false,
  deviceInfo: true,
} as DeviceDetector.DeviceDetectorOptions)

export { detector }
```
