### ISSUE TITLE
Amazon Echo user agents

### ISSUE THREAD

**Issue by mayurbhole** [sanchezzzhak/node-device-detector#8]
Amazon Echo devices are not identified. They have common regex pattern like "AEO[A-Z]{2,3}" 
Examples: 
`Mozilla/5.0 (Linux; Android 5.1.1; AEOKN Build/LVY48F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Safari/537.36`
`Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEOBC Build/LVY48F)`

**Comment by sanchezzzhak** [comment]
Hi
https://www.amazon.com/all-new-amazon-echo-speaker-with-wifi-alexa-dark-charcoal/dp/B06XCM9LJ4
This device, right?

**Comment by mayurbhole** [comment]
Yes

**Comment by mayurbhole** [comment]
Is this issue resolved?

**Comment by sanchezzzhak** [comment]
Hello, not resolved to
Add the device to the Motamo-org, and add it here automatically
