### ISSUE TITLE
r.readFileSync is not a function

### ISSUE THREAD

**Issue by malihakhizer** [sanchezzzhak/node-device-detector#84]
Hi, I am unable to use the package as it gives me error like in the attached picture
`const nodeDeviceDetector = require("node-device-detector");
  const aliasDeviceM = require("node-device-detector/parser/device/alias-device");

  const detector = new nodeDeviceDetector();
  var userAgent = "Mozilla/5.0 (Linux; Android 8.1; CLT-L29 Build/HUAWEICLT-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36";
  const result = detector.detect(userAgent);
  console.log("result parse", result);

  const aliasDevice = new aliasDeviceM();
  const result2 = aliasDevice.parse(userAgent);
  console.log("Result parse code model", result2);`
  
<img width="507" alt="image" src="https://user-images.githubusercontent.com/47573598/174625030-fc3e5bfc-fb0f-4128-aa97-9a3d4ce4a2c7.png">

**Comment by sanchezzzhak** [comment]
even if it works in the browser? there are several problems:
1 there will be problems with the lack of support https://caniuse.com/js-regexp-lookbehind (Safari for iOS hello)
2 large size for a web page

this library is intended for the server side only
