### ISSUE TITLE
Windows 11 detect

### ISSUE THREAD

**Issue by Bortnyak** [sanchezzzhak/node-device-detector#97]
Is there any way to detect windows 11 OS? 
For me, the library always detects windows 10 even though `ClientHints` is included in the parsing process.

**Comment by sanchezzzhak** [comment]
Hello.
Do you send clientHints headers to the user ?

you can go to this demo site https://iehol.sse.codesandbox.io/

send what you will have in the Header field
you may need to refresh the page 2 times.

**Comment by Bortnyak** [comment]
@sanchezzzhak Thank you for your fast reply.

**Comment by Bortnyak** [comment]
Yes, looks like my client application doesn't send the necessary headers to detect
